#!/bin/bash

for i in ~/.dotfiles/{aliases,functions,environment}/*.sh ; do
  source $i ;
done

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# load dev, but only if present and the shell is interactive
if [[ -f /opt/dev/dev.sh ]] && [[ $- == *i* ]]; then
  source /opt/dev/dev.sh
fi
