alias g="git"
alias ga="g add --all"
alias gc="g commit"
alias gs="g status"
alias gps="g push"
alias gpl="g pull"
alias gb="g branch -a"
alias gd="g diff"
alias gco="g checkout"
alias gl="g log"
alias gt="g log --graph --decorate --oneline --all"
alias gme='g config --local user.name "Volmer Soares" && git config --local user.email volmerius@gmail.com'
alias commit-image='ln -s ~/.bin/post-commit-image .git/hooks/post-commit'
